-- MySQL Script generated by MySQL Workbench
-- Fri Apr  2 14:49:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mamma-spa_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mamma-spa_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mamma-spa_db` DEFAULT CHARACTER SET utf8 ;
USE `mamma-spa_db` ;

-- -----------------------------------------------------
-- Table `mamma-spa_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamma-spa_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `type` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamma-spa_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamma-spa_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `price` INT NOT NULL,
  `brand` VARCHAR(30) NOT NULL,
  `img` VARCHAR(50) NOT NULL,
  `category_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `mamma-spa_db`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamma-spa_db`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamma-spa_db`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `price` INT NOT NULL,
  `img` VARCHAR(50) NOT NULL,
  `category_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `mamma-spa_db`.`categories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamma-spa_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamma-spa_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NULL DEFAULT NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `password2` VARCHAR(70) NOT NULL,
  `avatar` VARCHAR(50) NULL DEFAULT NULL,
  `role` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamma-spa_db`.`userscartproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamma-spa_db`.`userscartproducts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_product_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_user-cart_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user-cart_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mamma-spa_db`.`products` (`id`),
  CONSTRAINT `fk_user-cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mamma-spa_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mamma-spa_db`.`userscartservices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamma-spa_db`.`userscartservices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user-cart_service_idx` (`service_id` ASC) VISIBLE,
  INDEX `fk_user-cart_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user-cart_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `mamma-spa_db`.`services` (`id`),
  CONSTRAINT `fk_user-service-cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mamma-spa_db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
